### ISSUE TITLE
Website, description, topic, are missing.

### ISSUE THREAD

**Issue by ahojukka5** [JuliaFEM/MFrontInterface.jl#24]
![image](https://user-images.githubusercontent.com/1264779/66752570-6a75f380-ee9a-11e9-9252-15493497b2cf.png)

These help others to find a package. So kind of important information.

**Comment by ahojukka5** [comment]
I have been pointing website to latest documentation.

**Comment by TeroFrondelius** [comment]
![image](https://user-images.githubusercontent.com/12501534/66753554-c477b880-ee9c-11e9-9bcc-10c2e4514bcf.png)

Thanks.
